// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\gilsp\go\src\aqua-farm-manager\internal\domain\stat\stat.go

// Package mock_stat is a generated GoMock package.
package mock_stat

import (
	stat "aqua-farm-manager/internal/domain/stat"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStatDomain is a mock of StatDomain interface.
type MockStatDomain struct {
	ctrl     *gomock.Controller
	recorder *MockStatDomainMockRecorder
}

// MockStatDomainMockRecorder is the mock recorder for MockStatDomain.
type MockStatDomainMockRecorder struct {
	mock *MockStatDomain
}

// NewMockStatDomain creates a new mock instance.
func NewMockStatDomain(ctrl *gomock.Controller) *MockStatDomain {
	mock := &MockStatDomain{ctrl: ctrl}
	mock.recorder = &MockStatDomainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatDomain) EXPECT() *MockStatDomainMockRecorder {
	return m.recorder
}

// BackUpStat mocks base method.
func (m *MockStatDomain) BackUpStat() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BackUpStat")
}

// BackUpStat indicates an expected call of BackUpStat.
func (mr *MockStatDomainMockRecorder) BackUpStat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackUpStat", reflect.TypeOf((*MockStatDomain)(nil).BackUpStat))
}

// GenerateStatAPI mocks base method.
func (m *MockStatDomain) GenerateStatAPI() map[string]stat.StatMetrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStatAPI")
	ret0, _ := ret[0].(map[string]stat.StatMetrics)
	return ret0
}

// GenerateStatAPI indicates an expected call of GenerateStatAPI.
func (mr *MockStatDomainMockRecorder) GenerateStatAPI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStatAPI", reflect.TypeOf((*MockStatDomain)(nil).GenerateStatAPI))
}

// IngestStatAPI mocks base method.
func (m *MockStatDomain) IngestStatAPI(arg0 stat.IngestStatRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IngestStatAPI", arg0)
}

// IngestStatAPI indicates an expected call of IngestStatAPI.
func (mr *MockStatDomainMockRecorder) IngestStatAPI(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestStatAPI", reflect.TypeOf((*MockStatDomain)(nil).IngestStatAPI), arg0)
}

// MigrateStat mocks base method.
func (m *MockStatDomain) MigrateStat() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MigrateStat")
}

// MigrateStat indicates an expected call of MigrateStat.
func (mr *MockStatDomainMockRecorder) MigrateStat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateStat", reflect.TypeOf((*MockStatDomain)(nil).MigrateStat))
}
