// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\gilsp\go\src\aqua-farm-manager\internal\infrastructure\stat\stat.go

// Package mock_stat is a generated GoMock package.
package mock_stat

import (
	stat "aqua-farm-manager/internal/infrastructure/stat"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStatStore is a mock of StatStore interface.
type MockStatStore struct {
	ctrl     *gomock.Controller
	recorder *MockStatStoreMockRecorder
}

// MockStatStoreMockRecorder is the mock recorder for MockStatStore.
type MockStatStoreMockRecorder struct {
	mock *MockStatStore
}

// NewMockStatStore creates a new mock instance.
func NewMockStatStore(ctrl *gomock.Controller) *MockStatStore {
	mock := &MockStatStore{ctrl: ctrl}
	mock.recorder = &MockStatStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatStore) EXPECT() *MockStatStoreMockRecorder {
	return m.recorder
}

// BackupMetrics mocks base method.
func (m *MockStatStore) BackupMetrics(arg0 stat.BackupMetricsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupMetrics", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackupMetrics indicates an expected call of BackupMetrics.
func (mr *MockStatStoreMockRecorder) BackupMetrics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupMetrics", reflect.TypeOf((*MockStatStore)(nil).BackupMetrics), arg0)
}

// GetMetrics mocks base method.
func (m *MockStatStore) GetMetrics(arg0 stat.GetMetricsRequest) (stat.MetricsInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", arg0)
	ret0, _ := ret[0].(stat.MetricsInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockStatStoreMockRecorder) GetMetrics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockStatStore)(nil).GetMetrics), arg0)
}

// GetStatData mocks base method.
func (m *MockStatStore) GetStatData(arg0 stat.GetStatDataRequest) (stat.MetricsInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatData", arg0)
	ret0, _ := ret[0].(stat.MetricsInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatData indicates an expected call of GetStatData.
func (mr *MockStatStoreMockRecorder) GetStatData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatData", reflect.TypeOf((*MockStatStore)(nil).GetStatData), arg0)
}

// IngestMetrics mocks base method.
func (m *MockStatStore) IngestMetrics(arg0 stat.IngestMetricsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestMetrics", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestMetrics indicates an expected call of IngestMetrics.
func (mr *MockStatStoreMockRecorder) IngestMetrics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestMetrics", reflect.TypeOf((*MockStatStore)(nil).IngestMetrics), arg0)
}

// MigrateMetrics mocks base method.
func (m *MockStatStore) MigrateMetrics(arg0 stat.MigrateMetricsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateMetrics", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateMetrics indicates an expected call of MigrateMetrics.
func (mr *MockStatStoreMockRecorder) MigrateMetrics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateMetrics", reflect.TypeOf((*MockStatStore)(nil).MigrateMetrics), arg0)
}
